### ISSUE TITLE
com.google.protobuf.InvalidProtocolBufferException: Protocol message tag had invalid wire type.

### ISSUE THREAD

**Issue by zzbennett** [fatihmehmetkose/debezium-aws-rds-config-scripts#1]
Hi @fatihmehmetkose. First of all, this guide is so useful--thank you so much for putting it together.

I have everything set up but I'm running into this error when adding new records to the DB:

```
[2018-04-26 18:57:12,743] ERROR unexpected exception while streaming logical changes (io.debezium.connector.postgresql.RecordsStreamProducer:125)
java.lang.RuntimeException: com.google.protobuf.InvalidProtocolBufferException: Protocol message tag had invalid wire type.
	at io.debezium.connector.postgresql.connection.PostgresReplicationConnection$1.deserializeMessage(PostgresReplicationConnection.java:206)
	at io.debezium.connector.postgresql.connection.PostgresReplicationConnection$1.read(PostgresReplicationConnection.java:181)
	at io.debezium.connector.postgresql.RecordsStreamProducer.streamChanges(RecordsStreamProducer.java:112)
	at io.debezium.connector.postgresql.RecordsStreamProducer.lambda$start$1(RecordsStreamProducer.java:98)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message tag had invalid wire type.
	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:99)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:515)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:478)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:596)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:281)
	at com.google.protobuf.CodedInputStream.readGroup(CodedInputStream.java:424)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:505)
	at com.google.protobuf.GeneratedMessage.parseUnknownField(GeneratedMessage.java:205)
	at io.debezium.connector.postgresql.proto.PgProto$RowMessage.<init>(PgProto.java:2242)
	at io.debezium.connector.postgresql.proto.PgProto$RowMessage.<init>(PgProto.java:2199)
	at io.debezium.connector.postgresql.proto.PgProto$RowMessage$1.parsePartialFrom(PgProto.java:2327)
	at io.debezium.connector.postgresql.proto.PgProto$RowMessage$1.parsePartialFrom(PgProto.java:2322)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:137)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:168)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:180)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at io.debezium.connector.postgresql.proto.PgProto$RowMessage.parseFrom(PgProto.java:2603)
	at io.debezium.connector.postgresql.connection.PostgresReplicationConnection$1.deserializeMessage(PostgresReplicationConnection.java:204)
	... 8 more
```
I noticed in the debezium gitter that you ran into the same error as well. Did you ever figure out what the solution is?

**Comment by fatihmehmetkose** [comment]
Hi @zzbennett , 
It seems that "wal2json" replication slot configuration on PostgreSQL has some problem. Are you following the same instructions in this article or you have some other configuration files? 

The other reason might be the Debezium version you are using. In my experience, it is so important to use the latest stable version to get a successful result on Debezium. I was using DEBEZIUM_VERSION=0.7.1 and it was running without any problem. Please do not forget to export environment variable before running docker-compose commands.

**export DEBEZIUM_VERSION=0.7.1**
docker-compose down
docker-compose up

**Comment by zzbennett** [comment]
Thanks for your reply @fatihmehmetkose. My env is a little different, I'm not using docker, and I'm running kafka 0.11.0.0 (confluent platform 3.3.0). I installed debezium 0.6.2 because that version was built with kafka 0.11.0.0. I'm using AWS's postgres RDS. Besides the different versions, I followed your guide exactly (the screenshots in AWS were very useful btw).

I'll try using debezium 0.7.1 with the kafka version it is built with (1.0.0). I was hoping to get everything working with debezium 0.6.2 and kafka 0.11.0.0 so that I don't have to upgrade my production kafka deployment, but maybe this'll be a good excuse to upgrade everything anyways.

**Comment by mickdelaney** [comment]
@zzbennett did you get it to work ? 😀

**Comment by zzbennett** [comment]
I gave up working on it for now cause we realized we'd need to upgrade not only our kafka deployment, but also all our postgres db's. I think it probably would work though given what i read and given @fatihmehmetkose's experience.

**Comment by mickdelaney** [comment]
thanks @zzbennett
